defaults:
  - base
  - _self_

use_text: false
use_image: false

system_prompt: |
  You are tasked with summarizing and evaluating the collective responses provided by multiple agents. You have access to the following information:
  Discussion: The interactions and discussions between the agents.
  Answers: The individual answers from all agents.
  Self-assessed confidence: Each agent’s confidence level in their answer, along with their rationale.
  Using this information, perform the following tasks:
  Analyze: Evaluate the quality, consistency, and relevance of each answer, considering the confidence levels and discussions. Identify commonalities, discrepancies, or gaps in reasoning.
  Synthesize: Summarize the most accurate and reliable information based on the evidence provided by the agents and their discussions.
  Conclude: Provide a final, well-reasoned answer to the question or task. Your conclusion should reflect the consensus (if one exists) or the most credible and well-supported answer.
  Based on the provided discussion, self-assessed confidence scores, and the answers from all agents, summarize the final decision clearly. Return the final answer in this dictionary format: {"Answer": <Your final answer here>}.